
spring.application.name=alert-service
server.port=${ALERT_SERVICE_PORT:8081}

# ? Eureka
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ? MySQL
spring.datasource.url=${ALERT_SERVICE_DB:jdbc:mysql://localhost:3306/alerts_db?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${ALERT_SERVICE_DB_USERNAME:root}
spring.datasource.password=${ALERT_SERVICE_DB_PASSWORD:Tamaulipas69}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ? JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ? RabbitMQ
spring.rabbitmq.host=${RABBIT_HOST:localhost}
spring.rabbitmq.port=${RABBIT_PORT:5672}
spring.rabbitmq.username=${RABBIT_USERNAME:guest}
spring.rabbitmq.password=${RABBIT_PASSWORD:guest}
spring.rabbitmq.virtual-host=/

# ====================================================
# ===============  EVENTOS DE ALERTA  ================
# ====================================================

# Exchange principal de ALERTA
app.broker.exchange.alert=alert.exchange

# ---- ALERT DELETED (PROPIO) ----
app.broker.queue.alert.deleted=alert.deleted.queue
app.broker.routing-key.alert.deleted=alert.deleted

# ====================================================
# ===============  EVENTOS DE REPORT  ================
# ====================================================

# ---- REPORT DELETED ----
app.broker.queue.report.deleted=location.report.deleted.queue
app.broker.routing-key.report.deleted=report.deleted

# ---- REPORT REJECTED ----
app.broker.queue.report.rejected=location.report.rejected.queue
app.broker.routing-key.report.rejected=report.rejected
app.broker.queue.alert.rejected=alert.rejected.queue
app.broker.routing-key.alert.rejected=alert.rejected
